import type { Metadata } from "next";

import "./globals.css";
import { Bricolage_Grotesque } from "next/font/google";

const brico = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["200", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={brico.className}>{children}</body>
    </html>
  );
}
